### ISSUE TITLE
Comments from review of initial submission

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#124]
review comments/requests: see

- [x] Strengthen statement about "no objective system " for authorship #123 
- [x] further emphasize strikethrough formatting for errors in extant versions  #122 
- [x] maybe add a note about how manubot could be used for better lesson development #120 
- [x] "it is reviewed by a maintainer and a participant" #119 
- [x] "We use GitHub issues for organization"  #118 
- [x] "requesting modifications as depicted in 7." #117 
- [x] do rendered versions of each PR get posted back to the PR? #121 
- [x] footnote placement in rendered manuscript should be left-adjusted #116 
- [x] introductory paragraph needs more citations. #114
- [x] "correctness and fairness" in abstract are unclear. #115

note these refer to the submitted version of this paper that I received in PDF form; will need to be double checked against latest version.

**Comment by tpoisot** [comment]
I'd need to read a bit more to comment - just to be clear, is that an invitation to give feedback? I would be happy to, but I'm on parental leave until March.

**Comment by slochower** [comment]
Just checking, @ctb , is this an Issue that just links to other issues? If so, that's not really required. We can see the other issues just fine :)

**Comment by ctb** [comment]
I put this in to give the editor and other reviewer a single point of entry.

**Comment by slochower** [comment]
@ctb Yep, got it, sorry for the confusion. I was a little slow on figuring out what was going on.

**Comment by ctb** [comment]
I also wasn’t clear ;). Battling bad WI-FI and a plane about to take off! I’ll fix this issue up in a bit.

**Comment by ctb** [comment]
description & issue title fixed. please leave me to update the checkboxes for second review!

**Comment by agitter** [comment]
Thanks for the comments and for reorganizing the issue @ctb.  Would you like us to have you review the pull requests that we create to close these issues?  That would ensure we're addressing the comments properly, but I also don't want to commit you to more frequent reviewing if that isn't your intention.

**Comment by ctb** [comment]
> Would you like us to have you review the pull requests that we create to close these issues? That would ensure we're addressing the comments properly, but I also don't want to commit you to more frequent reviewing if that isn't your intention.

I'm traveling, so probably can't do much. But please ask for clarifications if needed!

**Comment by slochower** [comment]
@dhimmel @agitter Do you want to assign specific people to tackle specific issues or some other alternative strategy?

**Comment by dhimmel** [comment]
> Do you want to assign specific people to tackle specific issues or some other alternative strategy?

How about first one to volunteer or open a PR addressing a piece of feedback gets it. Let's try to keep PRs small, review fast, and merges frequent. @agitter did you want to create `response-to-reviewers.md` or should I?

**Comment by agitter** [comment]
> @agitter did you want to create `response-to-reviewers.md` or should I?

I'm on it now.  Sooo many meetings this week.

**Comment by agitter** [comment]
My plan for this issue is to start making pull requests to address the individual comments and close the respective issues.  Once they are all finished, we can discuss the batch of changes here and reopen issues that need more revisions.

**Comment by agitter** [comment]
@ctb thank you for all of your feedback on the Manubot manuscript and organizing it in issues.  We're getting close to resubmitting.  Is it okay with you if we acknowledge your public review (#126)?

We have also been checking the boxes above to help us track what still needs attention.  We're happy to discuss individual comments with you any time.

**Comment by ctb** [comment]
happy to be acknowledged!

**Comment by dhimmel** [comment]
Looks like we have made revisions to address each of the issues [above](https://github.com/greenelab/meta-review/issues/124#issue-406908296).

We can leave this open for @ctb to close if he agrees we've addressed the issues?

**Comment by agitter** [comment]
Closing this as part of the `v3.0` submission.  We could reopen or make new issues for additional discussion.
