### ISSUE TITLE
Manuscript revisions meta issue

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#151]
We received positive reviews on our manuscript and can use this issue to organize the revisions over the next few weeks.  Let's target resubmitting the week of March 4 or earlier.

All of the requested revisions are itemized below.  Following @dhimmel's suggestion, the first one to start a pull request to address a comment can claim it.  If there is something you know how to address, you can also assign yourself to the issue before making the pull request.  We may need to discuss some of these in the issue before we know edits to make.

We'll keep the pull requests small so they can be merged quickly, though I suggest leaving them open at least 12-24 hours so we can all monitor changes.

In addition to editing the manuscript, we now have a [`response-to-reviewers.md`](https://github.com/greenelab/meta-review/blob/master/content/response-to-reviewers.md).  Initially this document only has the quoted reviewer comments.  When you update the manuscript, please also add a summary of your changes to this point-by-point response letter.  See the examples in [deep-review](https://github.com/greenelab/deep-review/blob/master/content/response-to-reviewers.md) and [scihub](https://github.com/greenelab/scihub-manuscript/blob/master/content/response-to-reviewers.md).

Reviewer 1
- [x] Connecting Deep Review description https://github.com/greenelab/meta-review/issues/129

Reviewer 2
- [x] Non-technical readers https://github.com/greenelab/meta-review/issues/130
- [x] Mega papers https://github.com/greenelab/meta-review/issues/131
- [x] HTML output https://github.com/greenelab/meta-review/issues/132
- [x] Future vision https://github.com/greenelab/meta-review/issues/133
- [x] Template and fonts https://github.com/greenelab/meta-review/issues/134
- [x] Software archiving https://github.com/greenelab/meta-review/issues/135
- [x] Authorship credit https://github.com/greenelab/meta-review/issues/136
- [x] Pseudo authors https://github.com/greenelab/meta-review/issues/137
- [x] Private repositories https://github.com/greenelab/meta-review/issues/138
- [x] Editing through web interface https://github.com/greenelab/meta-review/issues/139
- [x] Anonymous review https://github.com/greenelab/meta-review/issues/140
- [x] Markdown limitations https://github.com/greenelab/meta-review/issues/141
- [x] Journal submission https://github.com/greenelab/meta-review/issues/142
- [x] Deep Review date https://github.com/greenelab/meta-review/issues/143
- [x] Deep Review duration https://github.com/greenelab/meta-review/issues/144
- [x] CC license https://github.com/greenelab/meta-review/issues/145
- [x] Collaborative editing tool features https://github.com/greenelab/meta-review/issues/146
- [x] WYSIWIG features https://github.com/greenelab/meta-review/issues/147
- [x] Figure 1 https://github.com/greenelab/meta-review/issues/148
- [x] Figure 2 https://github.com/greenelab/meta-review/issues/149
- [x] GitHub and Travis CI alternatives https://github.com/greenelab/meta-review/issues/150

Reviewer 3
- [x] Meta issue with 10 specific comments https://github.com/greenelab/meta-review/issues/124

Additional revisions
- [x] Update acknowledgements https://github.com/greenelab/meta-review/issues/126
- [x] Update authors https://github.com/greenelab/meta-review/issues/127
- [x] Update example manuscripts https://github.com/greenelab/meta-review/issues/128
- [x] Public demo manuscript #155
- [x] Upgrade Manubot #187
- [x] Authorea corrections #195
- [x] Update figshare video #207
- [x] Figure formats #209 
- [x] Manuscript diff #198
- [x] binder and v3.0 tag / release

cc @dhimmel @slochower @vsmalladi @vincerubinetti @dongbohu @cgreene

**Comment by agitter** [comment]
PLOS sent me a reminder that they would like the revision by March 7.  I can easily request an extension but would like to discuss our timeline for the revisions.  I should have more time to work on this over the next few weeks.

Can we start by going through the issues and making sure one or more of us has self-assigned to each one?

**Comment by slochower** [comment]
I'm going through a busy period at work, so I will be most effective if I can narrow my attention to a few Issues/PRs. 

I can add a little more text to #146.
#143 seems like low hanging fruit.
#142 seems like it's open ended. Probably need to narrow focus a bit -- presumably some journals no problem with format, some journals will not be happy.
#141 I can put the Pros/Cons in the text, but @dhimmel knows more about JATS and could fill in some other advantages.
#139 I could redo the mini-movie with some guidance from @agitter and @dhimmel on what they'd like to see.
#131 I can briefly mention these in a PR to the introduction.
#130 needs some thought.

**Comment by agitter** [comment]
Thanks @slochower, I'll look through some of the other issues you didn't mention and try to focus on those.  I'm fairly busy over the next week but may free up somewhat after that.

**Comment by vsmalladi** [comment]
I’m also just getting back from traveling so will take a look at other issue this week.

**Comment by agitter** [comment]
I requested more time for the revisions without specifying a specific new deadline.  I'm going to actively dig into the revisions Friday or Saturday and expect to make substantial progress the following week.

Can anyone help update Table 1 for #146 and #147?  We should make sure this table is still accurate with respect to the most recent versions of platforms like Overleaf that have changed a lot.

**Comment by agitter** [comment]
@dhimmel @slochower @vsmalladi @cgreene how feasible would it be for us to finish the meta review revisions in the next 7-10 days?  We made good progress over the past week.  I'd like to agree on a deadline so that we can wrap this up.

I'm going to go through the open issues and work on identifying a lead for each one.  That can help scope how much more time we need.

**Comment by slochower** [comment]
I think it's feasible. On a personal note, I will be traveling and giving two talks next week so I'm not entirely clear what my availability will be. If you can assign me Issues before this Sunday, I think I can more easily weave them into my downtime.

**Comment by dhimmel** [comment]
> how feasible would it be for us to finish the meta review revisions in the next 7-10 days?

I think wrapping things up in the next week is reasonable, and I'll aim for that. @agitter, I think you probably have the best handle on what's left to do. Feel free to assign me issues that you think I'll be the most effective in addressing.

**Comment by agitter** [comment]
We're getting very close now.  We have pull requests open for most of the remaining issues, and the others are small in scope.  I may try to finish the edits in the next couple days so that we can do a final review and resubmit April 7 or 8.

If anyone wants more time to review the new version, please let me know.

**Comment by agitter** [comment]
The journal emailed me again asking whether or not we plan to resubmit.  I'll tell them that we do plan to resubmit and it will be next week.  I'm targeting very early next week.

**Comment by agitter** [comment]
🎉 The resubmission is in! 🎉 

I'm leaving this open as a reminder that we need to update the `binder` tag and create the `v3.0` tag and release.

**Comment by slochower** [comment]
Thank you & everyone else for the hard work!

**Comment by agitter** [comment]
I updated the tags and am closing this issue.  The `binder` tag was originally 313023e4a6b713557163137b25cccb4f530ad919 and is now 4ef4d9fe9f85e90a232018b5aa111903449fd231.  That is the same commit as the [`v3.0` release](https://github.com/greenelab/meta-review/releases/tag/v3.0).

@dhimmel you can update the release notes if you'd like.  One consideration is whether we want to explain in the release notes why the tagged commit is one ahead of the commit we used for the diff.
